/*
 * DMARCForensicReport.java
 * Copyright (C) 2026 Chris Burdess
 *
 * This file is part of gumdrop, a multipurpose Java server.
 * For more information please visit https://www.nongnu.org/gumdrop/
 *
 * gumdrop is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * gumdrop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with gumdrop.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.bluezoo.gumdrop.smtp.auth;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.WritableByteChannel;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;

/**
 * RFC 7489 §7.2 — DMARC forensic (failure) report generator.
 *
 * <p>Generates a per-message failure report in the Abuse Reporting Format
 * (ARF, RFC 5965) with DMARC-specific extensions (RFC 6591). The report
 * is a {@code multipart/report} MIME message with three parts:
 *
 * <ol>
 *   <li>A human-readable text description of the failure</li>
 *   <li>A machine-readable {@code message/feedback-report} part containing
 *       structured fields per RFC 5965 §3.1 and RFC 6591 §3</li>
 *   <li>The original message headers (as {@code text/rfc822-headers}) or
 *       the full original message (as {@code message/rfc822})</li>
 * </ol>
 *
 * <p>Forensic reports are sent to the domain owner's {@code ruf=} address
 * when the DMARC record's {@code fo=} tag conditions are met:
 * <ul>
 *   <li>{@code fo=0} (default) — generate report if all mechanisms fail</li>
 *   <li>{@code fo=1} — generate report if any mechanism fails</li>
 *   <li>{@code fo=d} — generate report if DKIM fails (regardless of alignment)</li>
 *   <li>{@code fo=s} — generate report if SPF fails (regardless of alignment)</li>
 * </ul>
 *
 * <h4>Usage</h4>
 * <pre>{@code
 * DMARCForensicReport report = new DMARCForensicReport();
 * report.setReporterDomain("receiver.example.com");
 * report.setReporterEmail("postmaster@receiver.example.com");
 * report.setSourceIP("192.0.2.1");
 * report.setHeaderFrom("sender.example.com");
 * report.setEnvelopeFrom("bounce@sender.example.com");
 * report.setEnvelopeTo("user@receiver.example.com");
 * report.setAuthResults("dmarc=fail (p=reject) header.from=sender.example.com");
 * report.setDmarcResult(DMARCResult.FAIL);
 * report.setDmarcPolicy(DMARCPolicy.REJECT);
 * report.setSpfResult(SPFResult.FAIL);
 * report.setDkimResult(DKIMResult.FAIL);
 * report.setOriginalHeaders(headerBytes); // as delivered by MIMEHandler.bodyContent
 *
 * report.writeMIME(writableByteChannel, boundary);
 * }</pre>
 *
 * @author <a href='mailto:dog@gnu.org'>Chris Burdess</a>
 * @see DMARCValidator
 * @see DMARCAggregateReport
 * @see <a href="https://www.rfc-editor.org/rfc/rfc7489#section-7.2">RFC 7489 §7.2</a>
 * @see <a href="https://www.rfc-editor.org/rfc/rfc5965">RFC 5965 — ARF</a>
 * @see <a href="https://www.rfc-editor.org/rfc/rfc6591">RFC 6591 — ARF Extensions for Auth Failures</a>
 */
public class DMARCForensicReport {

    private static final String CRLF = "\r\n";

    // Every header/boundary/label line in this report is generated by
    // this class itself from ASCII-safe values (IPs, ASCII domains,
    // RFC 5322 dates, enum tokens) -- none of it is free text that
    // could require RFC 2047 encoding, so plain ASCII is sufficient
    // here. A field that did need to carry arbitrary text would use
    // org.bluezoo.gumdrop.mime.rfc2047.RFC2047Encoder rather than
    // hand-rolled encoding.
    private static final Charset ASCII = StandardCharsets.US_ASCII;

    private String reporterDomain;
    private String reporterEmail;
    private String sourceIP;
    private String headerFrom;
    private String envelopeFrom;
    private String envelopeTo;
    private String authResults;
    private DMARCResult dmarcResult;
    private DMARCPolicy dmarcPolicy;
    private SPFResult spfResult;
    private DKIMResult dkimResult;
    private String dkimDomain;
    /** FEAT-002: explicit alignment state for the Identity-Alignment field; null if not set. */
    private Boolean spfAligned;
    private Boolean dkimAligned;
    private ByteBuffer originalHeaders;
    private ByteBuffer originalMessage;
    private String messageId;
    private String subject;
    private Date arrivalDate;

    /** Sets the reporting domain (RFC 5965 §3.1 — Reported-Domain). */
    public void setReporterDomain(String domain) {
        this.reporterDomain = domain;
    }

    /** Sets the reporter's email for the From header of the report message. */
    public void setReporterEmail(String email) {
        this.reporterEmail = email;
    }

    /** Sets the source IP of the sending MTA (RFC 5965 §3.1 — Source-IP). */
    public void setSourceIP(String ip) {
        this.sourceIP = ip;
    }

    /** Sets the RFC5322.From domain of the original message. */
    public void setHeaderFrom(String from) {
        this.headerFrom = from;
    }

    /** Sets the envelope sender (MAIL FROM) of the original message. */
    public void setEnvelopeFrom(String from) {
        this.envelopeFrom = from;
    }

    /** Sets the envelope recipient (RCPT TO) of the original message. */
    public void setEnvelopeTo(String to) {
        this.envelopeTo = to;
    }

    /**
     * Sets the Authentication-Results header value
     * (RFC 5965 §3.1 — Authentication-Results).
     */
    public void setAuthResults(String results) {
        this.authResults = results;
    }

    /** Sets the DMARC evaluation result. */
    public void setDmarcResult(DMARCResult result) {
        this.dmarcResult = result;
    }

    /** Sets the DMARC policy from the domain's record. */
    public void setDmarcPolicy(DMARCPolicy policy) {
        this.dmarcPolicy = policy;
    }

    /** Sets the SPF evaluation result. */
    public void setSpfResult(SPFResult result) {
        this.spfResult = result;
    }

    /** Sets the DKIM verification result. */
    public void setDkimResult(DKIMResult result) {
        this.dkimResult = result;
    }

    /**
     * FEAT-002: RFC 9991 — sets whether SPF produced an aligned identifier
     * for this message (distinct from a raw SPF pass, which can occur
     * without the checked domain aligning to the From domain). Used for
     * the {@code Identity-Alignment} field; if never called, alignment is
     * approximated from {@link #setSpfResult} (pass = aligned), which is
     * only correct when the caller didn't perform relaxed-mode alignment
     * checking separately.
     *
     * @param aligned true if SPF passed and aligned
     * @see DMARCValidator#isLastSpfAligned()
     */
    public void setSpfAligned(boolean aligned) {
        this.spfAligned = aligned;
    }

    /**
     * FEAT-002: RFC 9991 — sets whether DKIM produced an aligned
     * identifier for this message. See {@link #setSpfAligned(boolean)}.
     *
     * @param aligned true if DKIM passed and aligned
     * @see DMARCValidator#isLastDkimAligned()
     */
    public void setDkimAligned(boolean aligned) {
        this.dkimAligned = aligned;
    }

    /** Sets the DKIM signing domain (d= tag), if available. */
    public void setDkimDomain(String domain) {
        this.dkimDomain = domain;
    }

    /**
     * Sets the original message headers for inclusion as
     * {@code text/rfc822-headers} (third MIME part).
     *
     * <p>This is verbatim wire content -- the exact bytes as received
     * (e.g. from {@link org.bluezoo.gumdrop.mime.MIMEHandler#bodyContent}
     * or an equivalent raw capture of the failing message), not text to
     * decode. A forensic report exists to show the analyst exactly what
     * was received, so the bytes are copied through unchanged rather
     * than being decoded to a String and later re-encoded, which would
     * risk corrupting anything outside the 7-bit ASCII range (e.g. an
     * 8BITMIME message or a legacy non-UTF-8 header encoding).
     *
     * @param headers the original header block bytes; a defensive copy
     *                is taken, so the caller's buffer may be reused
     *                immediately after this call returns
     */
    public void setOriginalHeaders(ByteBuffer headers) {
        this.originalHeaders = copyOf(headers);
    }

    /**
     * Sets the full original message for inclusion as {@code message/rfc822}
     * instead of headers only. If set, this takes precedence over
     * {@link #setOriginalHeaders}.
     *
     * <p>Verbatim wire content, copied through unchanged -- see
     * {@link #setOriginalHeaders(ByteBuffer)} for why this isn't a
     * {@code String}.
     *
     * @param message the original message bytes; a defensive copy is
     *                taken, so the caller's buffer may be reused
     *                immediately after this call returns
     */
    public void setOriginalMessage(ByteBuffer message) {
        this.originalMessage = copyOf(message);
    }

    /**
     * Copies the remaining bytes of {@code src} into a new, independent
     * buffer positioned at zero, without disturbing {@code src}'s own
     * position -- so the caller keeps full ownership of what it passed
     * in.
     */
    private static ByteBuffer copyOf(ByteBuffer src) {
        ByteBuffer copy = ByteBuffer.allocate(src.remaining());
        copy.put(src.duplicate());
        copy.flip();
        return copy;
    }

    /** Sets the Message-ID of the original message. */
    public void setMessageId(String id) {
        this.messageId = id;
    }

    /** Sets the Subject of the original message. */
    public void setSubject(String subj) {
        this.subject = subj;
    }

    /** Sets the arrival date of the original message. */
    public void setArrivalDate(Date date) {
        this.arrivalDate = date;
    }

    /**
     * RFC 7489 §7.2 — determines whether a forensic report should be
     * generated, based on the {@code fo=} tag value and the authentication
     * results.
     *
     * @param foTag the fo= tag value from the DMARC record ("0", "1", "d", "s"),
     *              or null for the default behaviour (fo=0)
     * @param spf the SPF result for this message
     * @param dkim the DKIM result for this message
     * @param dmarc the DMARC result for this message
     * @return true if a forensic report should be generated
     */
    public static boolean shouldReport(String foTag, SPFResult spf,
                                       DKIMResult dkim, DMARCResult dmarc) {
        if (foTag == null || foTag.isEmpty()) {
            foTag = "0";
        }

        for (int i = 0; i < foTag.length(); i++) {
            char c = foTag.charAt(i);
            if (c == ':') {
                continue;
            }
            switch (c) {
                case '0':
                    // All mechanisms fail to produce an aligned pass
                    if (dmarc == DMARCResult.FAIL) {
                        return true;
                    }
                    break;
                case '1':
                    // Any mechanism fails
                    if (spf != SPFResult.PASS || dkim != DKIMResult.PASS) {
                        return true;
                    }
                    break;
                case 'd':
                    // DKIM signature fails verification
                    if (dkim == DKIMResult.FAIL) {
                        return true;
                    }
                    break;
                case 's':
                    // SPF fails
                    if (spf == SPFResult.FAIL) {
                        return true;
                    }
                    break;
                default:
                    break;
            }
        }
        return false;
    }

    /**
     * RFC 7489 §7.2, RFC 5965 §3, RFC 6591 §3 — writes the forensic report
     * as a {@code multipart/report} MIME message body.
     *
     * <p>The caller is responsible for wrapping this in appropriate SMTP
     * envelope headers (To: ruf address, From: reporter, Subject, etc.)
     * and for the outer Content-Type with the boundary parameter.
     *
     * @param out the channel to write to
     * @param boundary the MIME boundary string to use
     * @throws IOException if an I/O error occurs
     */
    public void writeMIME(WritableByteChannel out, String boundary) throws IOException {
        // Part 1: Human-readable description
        write(out, "--" + boundary + CRLF, ASCII);
        write(out, "Content-Type: text/plain; charset=utf-8" + CRLF, ASCII);
        write(out, CRLF, ASCII);
        writeHumanReadable(out);
        write(out, CRLF, ASCII);

        // Part 2: Machine-readable feedback report (RFC 5965 §3.1, RFC 6591 §3)
        write(out, "--" + boundary + CRLF, ASCII);
        write(out, "Content-Type: message/feedback-report" + CRLF, ASCII);
        write(out, CRLF, ASCII);
        writeFeedbackReport(out);
        write(out, CRLF, ASCII);

        // Part 3: Original message or headers
        writeOriginalPart(out, boundary);

        // Closing boundary
        write(out, "--" + boundary + "--" + CRLF, ASCII);
    }

    /**
     * Encodes {@code s} with {@code charset} and drains the resulting
     * bytes to {@code out}, looping since a single channel write is
     * not guaranteed to consume the whole buffer.
     */
    private static void write(WritableByteChannel out, String s, Charset charset)
            throws IOException {
        ByteBuffer buf = ByteBuffer.wrap(s.getBytes(charset));
        while (buf.hasRemaining()) {
            out.write(buf);
        }
    }

    /**
     * Returns the Content-Type header value for the outer message.
     *
     * @param boundary the MIME boundary string
     * @return the Content-Type value
     */
    public String getContentType(String boundary) {
        return "multipart/report; report-type=feedback-report; boundary=\"" + boundary + "\"";
    }

    /** RFC 5965 §3.1 — human-readable part describing the failure. */
    private void writeHumanReadable(WritableByteChannel out) throws IOException {
        write(out, "This is a DMARC failure report for a message received from ", ASCII);
        write(out, sourceIP != null ? sourceIP : "unknown", ASCII);
        write(out, "." + CRLF, ASCII);
        write(out, CRLF, ASCII);
        if (headerFrom != null) {
            write(out, "The message claimed to be from: " + headerFrom + CRLF, ASCII);
        }
        if (dmarcResult != null) {
            write(out, "DMARC result: " + dmarcResult.getValue(), ASCII);
            if (dmarcPolicy != null) {
                write(out, " (policy=" + dmarcPolicy.toString().toLowerCase() + ")", ASCII);
            }
            write(out, CRLF, ASCII);
        }
        if (spfResult != null) {
            write(out, "SPF result: " + spfResult.getValue() + CRLF, ASCII);
        }
        if (dkimResult != null) {
            write(out, "DKIM result: " + dkimResult.getValue() + CRLF, ASCII);
        }
    }

    /**
     * RFC 5965 §3.1, RFC 6591 §3 — machine-readable feedback report fields.
     */
    private void writeFeedbackReport(WritableByteChannel out) throws IOException {
        // RFC 5965 §3.1 — required fields
        write(out, "Feedback-Type: auth-failure" + CRLF, ASCII);
        write(out, "User-Agent: gumdrop/DMARC" + CRLF, ASCII);
        write(out, "Version: 1" + CRLF, ASCII);

        // RFC 6591 §3 — Auth-Failure field
        if (dmarcResult == DMARCResult.FAIL) {
            write(out, "Auth-Failure: dmarc" + CRLF, ASCII);
        }

        if (sourceIP != null) {
            write(out, "Source-IP: " + sourceIP + CRLF, ASCII);
        }

        if (reporterDomain != null) {
            write(out, "Reported-Domain: " + reporterDomain + CRLF, ASCII);
        }

        if (reporterEmail != null) {
            write(out, "Report-Contact: " + reporterEmail + CRLF, ASCII);
        }

        // RFC 6591 §3 — policy and disposition
        if (dmarcPolicy != null) {
            String disposition;
            switch (dmarcPolicy) {
                case REJECT:
                    disposition = "reject";
                    break;
                case QUARANTINE:
                    disposition = "smg-quarantine";
                    break;
                default:
                    disposition = "delivered";
                    break;
            }
            write(out, "Delivery-Result: " + disposition + CRLF, ASCII);
        }

        if (headerFrom != null) {
            // RFC 9991 — comma-separated list of mechanisms that failed to
            // authenticate an aligned identity, or "none" if all did.
            write(out, "Identity-Alignment: " + computeIdentityAlignment() + CRLF, ASCII);
        }

        if (authResults != null) {
            write(out, "Authentication-Results: " + authResults + CRLF, ASCII);
        }

        // RFC 6591 §3 — original envelope attributes
        if (envelopeFrom != null) {
            write(out, "Original-Envelope-Id: " + envelopeFrom + CRLF, ASCII);
        }
        if (envelopeTo != null) {
            write(out, "Original-Rcpt-To: " + envelopeTo + CRLF, ASCII);
        }

        if (arrivalDate != null) {
            SimpleDateFormat sdf = new SimpleDateFormat(
                    "EEE, dd MMM yyyy HH:mm:ss Z", Locale.US);
            sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
            write(out, "Arrival-Date: " + sdf.format(arrivalDate) + CRLF, ASCII);
        }

        if (messageId != null) {
            write(out, "Original-Mail-From: " + (envelopeFrom != null ? envelopeFrom : "") + CRLF, ASCII);
        }

        // RFC 6591 §3 — DKIM-specific
        if (dkimDomain != null) {
            write(out, "DKIM-Domain: " + dkimDomain + CRLF, ASCII);
        }

        if (subject != null) {
            write(out, "Reported-URI: mid:" + (messageId != null ? messageId : "") + CRLF, ASCII);
        }
    }

    /**
     * FEAT-002: RFC 9991 — computes the Identity-Alignment field value:
     * a comma-separated list of mechanism names ("dkim", "spf") that
     * failed to authenticate an aligned identity, or "none" if all did.
     *
     * <p>Uses the explicit {@link #setSpfAligned}/{@link #setDkimAligned}
     * state if set (the correct source — see
     * {@link DMARCValidator#isLastSpfAligned()}); otherwise approximates
     * from the raw {@link #setSpfResult}/{@link #setDkimResult} pass/fail,
     * which is only accurate when alignment wasn't checked separately
     * from the mechanism's own pass/fail.
     */
    private String computeIdentityAlignment() {
        boolean dkimOk = dkimAligned != null ? dkimAligned : dkimResult == DKIMResult.PASS;
        boolean spfOk = spfAligned != null ? spfAligned : spfResult == SPFResult.PASS;

        if (dkimOk && spfOk) {
            return "none";
        }
        StringBuilder sb = new StringBuilder();
        if (!dkimOk) {
            sb.append("dkim");
        }
        if (!spfOk) {
            if (sb.length() > 0) {
                sb.append(',');
            }
            sb.append("spf");
        }
        return sb.toString();
    }

    /** Part 3: Original message headers or full message. */
    private void writeOriginalPart(WritableByteChannel out, String boundary) throws IOException {
        if (originalMessage != null) {
            // Full original message
            write(out, "--" + boundary + CRLF, ASCII);
            write(out, "Content-Type: message/rfc822" + CRLF, ASCII);
            write(out, CRLF, ASCII);
            writeBytes(out, originalMessage);
            write(out, CRLF, ASCII);
        } else if (originalHeaders != null) {
            // Headers only (privacy-preserving)
            write(out, "--" + boundary + CRLF, ASCII);
            write(out, "Content-Type: text/rfc822-headers" + CRLF, ASCII);
            write(out, CRLF, ASCII);
            writeBytes(out, originalHeaders);
            write(out, CRLF, ASCII);
        }
    }

    /**
     * Drains a verbatim copy of {@code data} to {@code out}, without
     * decoding or re-encoding a single byte -- {@code data} is already
     * wire content, not text.
     */
    private static void writeBytes(WritableByteChannel out, ByteBuffer data) throws IOException {
        ByteBuffer buf = data.duplicate();
        while (buf.hasRemaining()) {
            out.write(buf);
        }
    }

}
