/*
 * DTLSIntegrationTest.java
 * Copyright (C) 2026 Chris Burdess
 *
 * This file is part of gumdrop, a multipurpose Java server.
 * For more information please visit https://www.nongnu.org/gumdrop/
 *
 * gumdrop is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * gumdrop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with gumdrop.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.bluezoo.gumdrop.dtls;

import org.bluezoo.gumdrop.Endpoint;
import org.bluezoo.gumdrop.Gumdrop;
import org.bluezoo.gumdrop.ProtocolHandler;
import org.bluezoo.gumdrop.SecurityInfo;
import org.bluezoo.gumdrop.UDPEndpoint;
import org.bluezoo.gumdrop.UDPTransportFactory;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Paths;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;

import static org.junit.Assert.*;

/**
 * End-to-end test of DTLS support in {@link UDPEndpoint} (issue #190):
 * a real client and server, each with their own {@link UDPTransportFactory},
 * talking DTLSv1.2 over real loopback UDP sockets through a running
 * {@link Gumdrop} instance -- no mocking of the network or the SSLEngine.
 *
 * <p>Uses the same checked-in test PKI ({@code test/integration/certs/
 * test-keystore.p12} / {@code test-truststore.p12}, password {@code
 * testpass}) that the TCP/TLS integration tests use; see {@code
 * TestFixtureSetup} for how it's (re)generated by {@code ant
 * integration-setup}.
 *
 * @author <a href='mailto:dog@gnu.org'>Chris Burdess</a>
 */
public class DTLSIntegrationTest {

    private static final String CERTS_DIR = "test/integration/certs";
    private static final String KEYSTORE_PASSWORD = "testpass";
    private static final long TIMEOUT_SECONDS = 10;

    private Gumdrop gumdrop;
    private UDPEndpoint serverEndpoint;
    private UDPEndpoint clientEndpoint;

    @Before
    public void setUp() {
        File keystore = new File(CERTS_DIR, "test-keystore.p12");
        File truststore = new File(CERTS_DIR, "test-truststore.p12");
        assumeCertsExist(keystore, truststore);

        System.setProperty("gumdrop.workers", "2");
        gumdrop = Gumdrop.getInstance();
        if (!gumdrop.isStarted()) {
            gumdrop.start();
        }
    }

    private static void assumeCertsExist(File keystore, File truststore) {
        if (!keystore.exists() || !truststore.exists()) {
            throw new IllegalStateException(
                    "Test PKI not found; run 'ant integration-setup' first: "
                            + keystore + ", " + truststore);
        }
    }

    @After
    public void tearDown() {
        if (clientEndpoint != null) {
            clientEndpoint.close();
        }
        if (serverEndpoint != null) {
            serverEndpoint.close();
        }
    }

    /** Finds a free UDP port for the server to bind rather than hardcoding one. */
    private static int freePort() throws Exception {
        try (ServerSocket socket = new ServerSocket(0)) {
            return socket.getLocalPort();
        }
    }

    /** Echoes every decrypted application datagram straight back to its sender. */
    private static final class EchoHandler implements ProtocolHandler {
        volatile Endpoint endpoint;
        final List<String> received = new CopyOnWriteArrayList<String>();

        @Override
        public void receive(ByteBuffer data) {
            byte[] bytes = new byte[data.remaining()];
            data.get(bytes);
            received.add(new String(bytes, StandardCharsets.UTF_8));
            endpoint.send(ByteBuffer.wrap(bytes));
        }

        @Override
        public void connected(Endpoint endpoint) {
            this.endpoint = endpoint;
        }

        @Override
        public void disconnected() {
        }

        @Override
        public void securityEstablished(SecurityInfo info) {
        }

        @Override
        public void error(Exception cause) {
        }
    }

    /** Records the single reply the client expects back from the echo server. */
    private static final class ClientHandler implements ProtocolHandler {
        final CountDownLatch securityLatch = new CountDownLatch(1);
        final CountDownLatch replyLatch = new CountDownLatch(1);
        final AtomicReference<SecurityInfo> securityInfo = new AtomicReference<SecurityInfo>();
        final AtomicReference<String> reply = new AtomicReference<String>();
        volatile Endpoint endpoint;

        @Override
        public void receive(ByteBuffer data) {
            byte[] bytes = new byte[data.remaining()];
            data.get(bytes);
            reply.set(new String(bytes, StandardCharsets.UTF_8));
            replyLatch.countDown();
        }

        @Override
        public void connected(Endpoint endpoint) {
            this.endpoint = endpoint;
        }

        @Override
        public void disconnected() {
        }

        @Override
        public void securityEstablished(SecurityInfo info) {
            securityInfo.set(info);
            securityLatch.countDown();
        }

        @Override
        public void error(Exception cause) {
        }
    }

    @Test
    public void testHandshakeAndEchoRoundTrip() throws Exception {
        File keystore = new File(CERTS_DIR, "test-keystore.p12");
        File truststore = new File(CERTS_DIR, "test-truststore.p12");
        int port = freePort();

        UDPTransportFactory serverFactory = new UDPTransportFactory();
        serverFactory.setSecure(true);
        serverFactory.setKeystoreFile(Paths.get(keystore.getPath()));
        serverFactory.setKeystorePass(KEYSTORE_PASSWORD);
        serverFactory.start();

        EchoHandler echoHandler = new EchoHandler();
        serverEndpoint = serverFactory.createServerEndpoint(null, port, echoHandler);

        UDPTransportFactory clientFactory = new UDPTransportFactory();
        clientFactory.setSecure(true);
        // Every secure TransportFactory (TCP and UDP alike) requires its
        // own keystore even when acting purely as a client -- see
        // UDPTransportFactory.start()/TCPTransportFactory.start(). The
        // client engine only presents this identity if the server
        // actually requests client-cert auth, which this test's server
        // does not, so reusing the same test identity here is harmless.
        clientFactory.setKeystoreFile(Paths.get(keystore.getPath()));
        clientFactory.setKeystorePass(KEYSTORE_PASSWORD);
        clientFactory.setTruststoreFile(Paths.get(truststore.getPath()));
        clientFactory.setTruststorePass(KEYSTORE_PASSWORD);
        clientFactory.start();

        ClientHandler clientHandler = new ClientHandler();
        clientEndpoint = clientFactory.connect(
                InetAddress.getLoopbackAddress(), port, clientHandler);

        assertTrue("DTLS handshake should complete and notify the client",
                clientHandler.securityLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
        assertEquals("DTLSv1.2", clientHandler.securityInfo.get().getProtocol());

        clientEndpoint.send(ByteBuffer.wrap("hello over DTLS".getBytes(StandardCharsets.UTF_8)));

        assertTrue("client should have received the echoed reply",
                clientHandler.replyLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
        assertEquals("hello over DTLS", clientHandler.reply.get());
        assertEquals("server should have decrypted exactly one datagram",
                1, echoHandler.received.size());
        assertEquals("hello over DTLS", echoHandler.received.get(0));
    }

    @Test
    public void testTwoConcurrentClientsGetIndependentSessions() throws Exception {
        File keystore = new File(CERTS_DIR, "test-keystore.p12");
        File truststore = new File(CERTS_DIR, "test-truststore.p12");
        int port = freePort();

        UDPTransportFactory serverFactory = new UDPTransportFactory();
        serverFactory.setSecure(true);
        serverFactory.setKeystoreFile(Paths.get(keystore.getPath()));
        serverFactory.setKeystorePass(KEYSTORE_PASSWORD);
        serverFactory.start();

        EchoHandler echoHandler = new EchoHandler();
        serverEndpoint = serverFactory.createServerEndpoint(null, port, echoHandler);

        // See the comment in testHandshakeAndEchoRoundTrip: every secure
        // TransportFactory needs its own keystore even as a client-only user.
        UDPTransportFactory clientFactory1 = new UDPTransportFactory();
        clientFactory1.setSecure(true);
        clientFactory1.setKeystoreFile(Paths.get(keystore.getPath()));
        clientFactory1.setKeystorePass(KEYSTORE_PASSWORD);
        clientFactory1.setTruststoreFile(Paths.get(truststore.getPath()));
        clientFactory1.setTruststorePass(KEYSTORE_PASSWORD);
        clientFactory1.start();

        UDPTransportFactory clientFactory2 = new UDPTransportFactory();
        clientFactory2.setSecure(true);
        clientFactory2.setKeystoreFile(Paths.get(keystore.getPath()));
        clientFactory2.setKeystorePass(KEYSTORE_PASSWORD);
        clientFactory2.setTruststoreFile(Paths.get(truststore.getPath()));
        clientFactory2.setTruststorePass(KEYSTORE_PASSWORD);
        clientFactory2.start();

        ClientHandler client1Handler = new ClientHandler();
        ClientHandler client2Handler = new ClientHandler();
        clientEndpoint = clientFactory1.connect(InetAddress.getLoopbackAddress(), port, client1Handler);
        UDPEndpoint clientEndpoint2 = clientFactory2.connect(
                InetAddress.getLoopbackAddress(), port, client2Handler);
        try {
            assertTrue(client1Handler.securityLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
            assertTrue(client2Handler.securityLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));

            clientEndpoint.send(ByteBuffer.wrap("from client one".getBytes(StandardCharsets.UTF_8)));
            clientEndpoint2.send(ByteBuffer.wrap("from client two".getBytes(StandardCharsets.UTF_8)));

            assertTrue(client1Handler.replyLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
            assertTrue(client2Handler.replyLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));

            assertEquals("from client one", client1Handler.reply.get());
            assertEquals("from client two", client2Handler.reply.get());
        } finally {
            clientEndpoint2.close();
        }
    }

}
