/*
 * ResolvConf.java
 * Copyright (C) 2026 Chris Burdess
 *
 * This file is part of gumdrop, a multipurpose Java server.
 * For more information please visit https://www.nongnu.org/gumdrop/
 *
 * gumdrop is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * gumdrop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with gumdrop.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.bluezoo.gumdrop.dns.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Platform-aware parser for the system DNS resolver configuration
 * ({@code /etc/resolv.conf} on POSIX systems).
 *
 * <p>Only {@code nameserver} directives are extracted; other resolv.conf
 * directives ({@code search}, {@code domain}, {@code sortlist},
 * {@code options}, etc.) are ignored. Returned values are the raw address
 * tokens as they appear in the file, in file order; they are not validated
 * as IP literals here -- callers (e.g. {@link DNSResolver#addServer}) are
 * expected to validate and skip invalid entries themselves.
 *
 * <p>On macOS, {@code /etc/resolv.conf} is dynamically generated by
 * mDNSResponder and can be stale or incomplete under VPN or DNS-over-HTTPS
 * profiles; this class reads it directly rather than shelling out to
 * {@code scutil --dns}, accepting that as a known limitation.
 *
 * <p>On Windows, there is no equivalent configuration file; {@link
 * #getNameservers} always returns an empty list there.
 *
 * <p>This class is a shared singleton. The file is parsed lazily on first
 * access and the result is cached in memory.
 *
 * @author <a href='mailto:dog@gnu.org'>Chris Burdess</a>
 */
public final class ResolvConf {

    private static final Logger LOGGER = Logger.getLogger(ResolvConf.class.getName());

    private static volatile List<String> nameservers;

    private ResolvConf() {
    }

    /**
     * Returns the system's configured DNS nameservers as address strings,
     * in the order they appear in the resolver configuration.
     *
     * @return an unmodifiable list of address strings, never null; empty if
     * none were found or the platform has no equivalent configuration file
     */
    public static List<String> getNameservers() {
        List<String> list = nameservers;
        if (list != null) {
            return list;
        }
        synchronized (ResolvConf.class) {
            if (nameservers != null) {
                return nameservers;
            }
            nameservers = parse(locateResolvConf());
            return nameservers;
        }
    }

    /**
     * Clears the cached nameserver list, forcing a re-read on next access.
     */
    static void clear() {
        nameservers = null;
    }

    /**
     * Eagerly parses and caches the system resolver configuration.
     *
     * <p>Call once during server startup (off any {@code SelectorLoop}) so
     * the first DNS resolve after accept cannot stall a reactor thread on
     * {@code /etc/resolv.conf} I/O. Subsequent {@link #getNameservers}
     * calls use the in-memory cache.
     */
    public static void warm() {
        getNameservers();
    }

    /**
     * Parses a resolv.conf-formatted file, extracting {@code nameserver}
     * directive values in file order. Package-private test seam; performs
     * no caching.
     *
     * @param path the file to parse, or null
     * @return an unmodifiable list of address strings, never null
     */
    static List<String> parse(Path path) {
        if (path == null || !Files.exists(path)) {
            return Collections.emptyList();
        }
        List<String> list = new ArrayList<>();
        try {
            BufferedReader reader = Files.newBufferedReader(path);
            try {
                String line;
                while ((line = reader.readLine()) != null) {
                    // resolv.conf comments may start with '#' or ';'
                    int hash = line.indexOf('#');
                    int semi = line.indexOf(';');
                    int comment = (hash < 0) ? semi
                            : (semi < 0) ? hash : Math.min(hash, semi);
                    if (comment >= 0) {
                        line = line.substring(0, comment);
                    }
                    line = line.trim();
                    if (line.isEmpty()) {
                        continue;
                    }
                    String[] parts = line.split("\\s+");
                    if (parts.length < 2 || !"nameserver".equals(parts[0])) {
                        continue;
                    }
                    list.add(parts[1]);
                }
            } finally {
                reader.close();
            }
        } catch (IOException e) {
            LOGGER.log(Level.FINE, "Could not read resolver configuration: " + path, e);
        }
        return Collections.unmodifiableList(list);
    }

    private static Path locateResolvConf() {
        String os = System.getProperty("os.name", "").toLowerCase();
        if (os.contains("win")) {
            // No pure-Java equivalent of GetNetworkParams(); callers fall
            // back to well-known public resolvers.
            return null;
        }
        return Paths.get("/etc/resolv.conf");
    }

}
